openapi: 3.1.0
x-stoplight:
  id: ejsqv3lxdpyd5
info:
  title: ProductAPI
  version: '1.0'
  summary: ECommerce Platform API
  description: A comprehensive CRUD API for managing products in an eCommerce platform.
  license:
    url: 'http://www.apache.org/license/LICENSE-2.0'
    name: Apache 2.0
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/getProduct/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: Product Id
    get:
      summary: Get Product Info by Product ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Product Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      operationId: getProductById
      description: Retrieve the information of the Product with the matching Product ID.
      x-stoplight:
        id: xzs4qwrethw6f
      parameters: []
  /api/addProduct:
    post:
      summary: Add a new Product
      operationId: createProduct
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                Example 1:
                  value:
                    productId: 1
                    name: The Discovery of India
                    description: Non-Fiction
                    price: 365
                    quantityAvailable: 40
        '400':
          description: Missing Required Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
              x-examples:
                Example 1:
                  name: The Chronicles of Narnia
                  description: Fiction
                  price: 120
                  quantityAvailable: 40
            examples: {}
        description: ''
      description: creates a new Product
      x-stoplight:
        id: w6j1l0opwd2fd
      parameters: []
    parameters: []
  '/api/deleteProduct/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: Product Id
    delete:
      summary: Delete a Product
      operationId: deleteProduct
      responses:
        '200':
          description: Product Deleted Successfully
          content:
            application/json:
              schema:
                type: string
              examples:
                Example 1:
                  value: Product Deleted Successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      x-stoplight:
        id: fhgji6bj7a8at
      description: "To delete an existing product.\r\n"
      parameters: []
  /api/getAllProducts:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                x-examples:
                  Example 1:
                    - productId: 1
                      name: The Discovery of India
                      description: Non-Fiction
                      price: 365
                      quantityAvailable: 40
                    - productId: 2
                      name: The Adventure
                      description: Fiction
                      price: 280
                      quantityAvailable: 75
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      operationId: getAllProducts
      x-stoplight:
        id: oe58uc896l1xv
      parameters: []
      description: Retrive all products
    parameters: []
  '/api/updateProduct/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: Product Id
    patch:
      summary: Update Product Information
      tags: []
      responses:
        '200':
          description: Product information Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      operationId: updateProduct
      x-stoplight:
        id: iq1auq48th47n
      description: Update the information of an existing product.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
              x-examples:
                Example 1:
                  quantityAvailable: 80
              description: Updated Product Info
            examples:
              Update Product Name:
                value:
                  name: Wings Of Fire
              Update Price:
                value:
                  price: 400
              Update Quantity:
                value:
                  quantityAvailable: 80
              Update Description:
                value:
                  description: Non-Fiction
  '/api/applyDiscount/{id}':
    patch:
      summary: Apply Discount
      operationId: applyDiscount
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      x-stoplight:
        id: 82o4e63v5r44m
      description: Apply Discount to promote sales
      parameters:
        - schema:
            type: number
            format: double
          in: header
          name: DiscountPercentage
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: Product Id
  '/api/applyTax/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: Product Id
    patch:
      summary: Apply Tax
      operationId: applyTax
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      x-stoplight:
        id: weevr70c8fyum
      description: Apply tax for regulatory compliance
      parameters:
        - schema:
            type: number
            format: double
          in: header
          name: TaxRate
components:
  schemas:
    GenericResponse:
      type: object
      x-examples:
        Example 1:
          code: '500'
          message: Internal Server Error
      properties:
        code:
          type: string
          pattern: '^[0-9]+$'
        message:
          type: string
    Product:
      type: object
      x-examples:
        Example 1:
          productId: 1
          name: The Discovery of India
          description: Non-Fiction
          price: 365
          quantityAvailable: 40
      description: Product Catalog
      properties:
        productId:
          type: integer
          format: int64
          description: Unique Identifier for the product
          readOnly: true
        name:
          type: string
          description: Product Name
        description:
          type: string
          description: Description of the product
        price:
          type: number
          description: Price of the product
          format: double
          minimum: 0
        quantityAvailable:
          type: integer
          description: Available quantity of the product
          minimum: 0
  securitySchemes: {}
